version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=mysql://default:default@db/zpt_digital

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'zpt_digital'
      MYSQL_USER: 'default'
      MYSQL_PASSWORD: 'default'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"  # Mapeie a porta 8081 do host para a porta 80 do phpMyAdmin

volumes:
  db_data:
